//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionMedicamentoInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rol()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idRol { get; set; }
        public bool categoriaCreate { get; set; }
        public bool categoriaDelete { get; set; }
        public bool categoriaDetails { get; set; }
        public bool categoriaEdit { get; set; }
        public bool categoriaIndex { get; set; }
        public bool comprasCreate { get; set; }
        public bool comprasDelete { get; set; }
        public bool comprasDetails { get; set; }
        public bool comprasEdit { get; set; }
        public bool comprasIndex { get; set; }
        public bool descuentoCreate { get; set; }
        public bool descuentoDelete { get; set; }
        public bool descuentoDetails { get; set; }
        public bool descuentoEdit { get; set; }
        public bool descuentoIndex { get; set; }
        public bool detallesCreate { get; set; }
        public bool detallesDelete { get; set; }
        public bool detallesDetails { get; set; }
        public bool detallesEdit { get; set; }
        public bool detallesIndex { get; set; }
        public bool empresaCreate { get; set; }
        public bool empresaDelete { get; set; }
        public bool empresaDetails { get; set; }
        public bool empresaEdit { get; set; }
        public bool empresaIndex { get; set; }
        public bool inventarioCreate { get; set; }
        public bool inventarioDelete { get; set; }
        public bool inventarioDetails { get; set; }
        public bool inventarioEdit { get; set; }
        public bool inventarioIndex { get; set; }
        public bool kardexCreate { get; set; }
        public bool kardexDelete { get; set; }
        public bool kardexDetails { get; set; }
        public bool kardexEdit { get; set; }
        public bool kardexIndex { get; set; }
        public bool loteCreate { get; set; }
        public bool loteoDelete { get; set; }
        public bool loteDetails { get; set; }
        public bool loteEdit { get; set; }
        public bool loteIndex { get; set; }
        public bool medicamentoCreate { get; set; }
        public bool medicamentoDelete { get; set; }
        public bool medicamentoDetails { get; set; }
        public bool medicamentoEdit { get; set; }
        public bool medicamentoIndex { get; set; }
        public bool rolCreate { get; set; }
        public bool rolDelete { get; set; }
        public bool rolDetails { get; set; }
        public bool rolEdit { get; set; }
        public bool rolIndex { get; set; }
        public bool usuarioCreate { get; set; }
        public bool usuarioDelete { get; set; }
        public bool usuarioDetails { get; set; }
        public bool usuarioEdit { get; set; }
        public bool usuarioIndex { get; set; }
        public bool ventasCreate { get; set; }
        public bool ventasDelete { get; set; }
        public bool ventasDetails { get; set; }
        public bool ventasEdit { get; set; }
        public bool ventasIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
