//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace GestionMedicamentoInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Empresa = new HashSet<Empresa>();
        }
    
        public int idUsuario { get; set; }
        [Display(Name ="Nombre")]
        public string nombreUsuario { get; set; }
        [Display(Name = "Apellido")]
        public string apellidoUsuario { get; set; }
        [Display(Name = "Email")]
        public string email { get; set; }
        [Display(Name = "Telefono")]
        public string telefono { get; set; }
        [Display(Name = "Rol")]
        public Nullable<int> idRol { get; set; }
        [Display(Name = "Contraseña")]
        public string password { get; set; }
        [Display(Name = "Nombre de Usuario")]
        public string userName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
