//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace GestionMedicamentoInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int idVenta { get; set; }
        [Display(Name = "Cantidad")]
        public Nullable<decimal> cantidad { get; set; }
        [Display(Name = "Precio")]
        public Nullable<decimal> precioVenta { get; set; }
        [Display(Name = "Descuento")]
        public Nullable<int> idDescuento { get; set; }
        [Display(Name = "Id Lote")]
        public Nullable<int> idLote { get; set; }
        [Display(Name = "Medicamento")]
        public Nullable<int> idKardex { get; set; }
        [Display(Name = "Fecha")]
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Descuento Descuento { get; set; }
        public virtual Kardex Kardex { get; set; }
        public virtual Lote Lote { get; set; }
    }
}
